# Generated by Django 4.2.23 on 2025-09-03 01:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('arpia_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='observedendpoint',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
