# Generated by Django 4.2.25 on 2025-10-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arpia_core', '0003_project_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembership',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
