# Generated by Django 4.2.24 on 2025-10-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arpia_scan', '0002_add_report_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scantask',
            name='kind',
            field=models.CharField(choices=[('connectivity', 'Teste de conectividade'), ('discovery_rustscan', 'Descoberta rápida (Rustscan)'), ('discovery_nmap', 'Níveis de ruído (Nmap)'), ('script', 'Execução de script'), ('custom', 'Personalizado')], default='custom', max_length=40),
        ),
    ]
