# Generated by Django 4.2.24 on 2025-10-13 21:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('source_app', models.CharField(db_index=True, max_length=64)),
                ('component', models.CharField(blank=True, max_length=128)),
                ('event_type', models.CharField(db_index=True, max_length=128)),
                ('severity', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('NOTICE', 'Notice'), ('WARN', 'Warn'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=16)),
                ('message', models.CharField(max_length=512)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('correlation', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('project_ref', models.CharField(blank=True, db_index=True, max_length=128)),
                ('asset_ref', models.CharField(blank=True, max_length=128)),
                ('user_ref', models.CharField(blank=True, max_length=128)),
                ('ingestion_channel', models.CharField(choices=[('internal', 'Internal'), ('api', 'API'), ('batch', 'Batch')], default='internal', max_length=16)),
                ('ingested_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
                'indexes': [models.Index(fields=['source_app', 'timestamp'], name='idx_log_src_ts'), models.Index(fields=['event_type', 'timestamp'], name='idx_log_evt_ts'), models.Index(fields=['project_ref', 'timestamp'], name='idx_log_project_ts'), models.Index(fields=['severity', 'timestamp'], name='idx_log_sev_ts')],
            },
        ),
    ]
