# Generated by Django 4.2.24 on 2025-10-29 02:48

import arpia_vuln.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arpia_scan', '0003_alter_scantask_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arpia_core', '0007_script_required_tool'),
    ]

    operations = [
        migrations.CreateModel(
            name='VulnScanSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(default=arpia_vuln.models._default_reference, editable=False, max_length=32, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('planned', 'Planejada'), ('ready', 'Pronta'), ('running', 'Em execução'), ('completed', 'Concluída'), ('failed', 'Falhou'), ('canceled', 'Cancelada')], default='planned', max_length=20)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('targets_snapshot', models.JSONField(blank=True, default=dict)),
                ('report_snapshot', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuln_sessions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuln_sessions', to='arpia_core.project')),
                ('source_scan_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vulnerability_sessions', to='arpia_scan.scansession')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='VulnTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('kind', models.CharField(choices=[('discovery_nmap', 'Discovery (Nmap)'), ('service_enum', 'Enumeração de serviços'), ('greenbone_scan', 'Greenbone'), ('script', 'Script'), ('custom', 'Personalizado')], default='custom', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('queued', 'Na fila'), ('running', 'Em execução'), ('completed', 'Concluída'), ('failed', 'Falhou'), ('canceled', 'Cancelada')], default='pending', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('progress', models.FloatField(default=0.0)),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('script', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vuln_tasks', to='arpia_core.script')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='arpia_vuln.vulnscansession')),
                ('tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vuln_tasks', to='arpia_core.tool')),
            ],
            options={
                'ordering': ('session', 'order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='VulnerabilityFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve', models.CharField(blank=True, max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('critical', 'Crítica'), ('high', 'Alta'), ('medium', 'Média'), ('low', 'Baixa'), ('info', 'Informativa'), ('unknown', 'Indefinida')], default='unknown', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('ack', 'Reconhecida'), ('resolved', 'Resolvida')], default='open', max_length=16)),
                ('host', models.CharField(blank=True, max_length=200)),
                ('service', models.CharField(blank=True, max_length=200)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, max_length=12)),
                ('cvss_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('cvss_vector', models.CharField(blank=True, max_length=128)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='arpia_vuln.vulnscansession')),
                ('source_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='arpia_vuln.vulntask')),
            ],
            options={
                'ordering': ('session', '-cvss_score', 'severity', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='vulntask',
            index=models.Index(fields=['session', 'kind'], name='idx_vuln_task_session_kind'),
        ),
        migrations.AddIndex(
            model_name='vulntask',
            index=models.Index(fields=['status', 'updated_at'], name='idx_vuln_task_status'),
        ),
        migrations.AddIndex(
            model_name='vulnscansession',
            index=models.Index(fields=['project', 'created_at'], name='idx_vuln_session_project'),
        ),
        migrations.AddIndex(
            model_name='vulnscansession',
            index=models.Index(fields=['status', 'created_at'], name='idx_vuln_session_status'),
        ),
        migrations.AddIndex(
            model_name='vulnerabilityfinding',
            index=models.Index(fields=['session', 'severity'], name='idx_vuln_finding_severity'),
        ),
        migrations.AddIndex(
            model_name='vulnerabilityfinding',
            index=models.Index(fields=['cve'], name='idx_vuln_finding_cve'),
        ),
        migrations.AddIndex(
            model_name='vulnerabilityfinding',
            index=models.Index(fields=['host', 'port'], name='idx_vuln_finding_target'),
        ),
    ]
