# Generated by Django 4.2.24 on 2025-10-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arpia_vuln', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnscansession',
            name='macros_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
