# Generated by Django 4.2.25 on 2025-11-01 00:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arpia_core', '0007_script_required_tool'),
        ('arpia_scan', '0003_alter_scantask_kind'),
        ('arpia_vuln', '0002_vulnscansession_macros_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='HuntSyncLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('success', 'Sucesso'), ('error', 'Erro')], default='success', max_length=12)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('total_processed', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hunt_sync_runs', to='arpia_core.project')),
            ],
            options={
                'ordering': ('-started_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='HuntFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('host', models.CharField(blank=True, max_length=200)),
                ('service', models.CharField(blank=True, max_length=200)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, max_length=12)),
                ('cve', models.CharField(blank=True, max_length=40)),
                ('severity', models.CharField(choices=[('critical', 'Crítica'), ('high', 'Alta'), ('medium', 'Média'), ('low', 'Baixa'), ('info', 'Informativa'), ('unknown', 'Indefinida')], default='unknown', max_length=16)),
                ('cvss_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('cvss_vector', models.CharField(blank=True, max_length=128)),
                ('summary', models.TextField(blank=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('source_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('detected_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hunt_findings', to='arpia_core.asset')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunt_findings', to='arpia_core.project')),
                ('scan_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hunt_findings', to='arpia_scan.scansession')),
                ('vuln_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hunt_findings', to='arpia_vuln.vulnscansession')),
                ('vulnerability', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hunt_finding', to='arpia_vuln.vulnerabilityfinding')),
            ],
            options={
                'ordering': ('-detected_at', '-cvss_score', '-created_at'),
                'indexes': [models.Index(fields=['project', 'severity'], name='idx_hunt_finding_project_sev'), models.Index(fields=['cve'], name='idx_hunt_finding_cve'), models.Index(fields=['host', 'port'], name='idx_hunt_finding_target')],
            },
        ),
    ]
