# Generated by Django 4.2.24 on 2025-11-01 00:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('arpia_hunt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HuntEnrichment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cve', models.CharField(db_index=True, max_length=40)),
                ('source', models.CharField(choices=[('nvd', 'NVD'), ('vulners', 'Vulners'), ('exploitdb', 'Exploit DB')], max_length=16)),
                ('status', models.CharField(choices=[('fresh', 'Atualizado'), ('stale', 'Expirado'), ('error', 'Erro'), ('skipped', 'Ignorado')], default='fresh', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at', '-id'),
                'indexes': [models.Index(fields=['source', 'status'], name='idx_hunt_enrich_src_status'), models.Index(fields=['expires_at'], name='idx_hunt_enrich_exp')],
                'unique_together': {('cve', 'source')},
            },
        ),
    ]
