# Generated by Django 4.2.24 on 2025-11-01 01:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('arpia_hunt', '0002_huntenrichment'),
    ]

    operations = [
        migrations.AddField(
            model_name='huntfinding',
            name='blue_profile',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='huntfinding',
            name='last_profiled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='huntfinding',
            name='profile_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='huntfinding',
            name='red_profile',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='HuntFindingEnrichment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('relation', models.CharField(choices=[('general', 'Referência'), ('blue', 'Blue-Team'), ('red', 'Red-Team'), ('exploit', 'Exploit')], default='general', max_length=16)),
                ('linked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('enrichment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finding_links', to='arpia_hunt.huntenrichment')),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrichment_links', to='arpia_hunt.huntfinding')),
            ],
            options={
                'ordering': ('-last_synced_at', '-id'),
                'unique_together': {('finding', 'enrichment')},
            },
        ),
        migrations.AddField(
            model_name='huntfinding',
            name='enrichments',
            field=models.ManyToManyField(blank=True, related_name='findings', through='arpia_hunt.HuntFindingEnrichment', to='arpia_hunt.huntenrichment'),
        ),
        migrations.CreateModel(
            name='HuntFindingSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('blue_profile', models.JSONField(blank=True, default=dict)),
                ('red_profile', models.JSONField(blank=True, default=dict)),
                ('enrichment_ids', models.JSONField(blank=True, default=list)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='arpia_hunt.huntfinding')),
            ],
            options={
                'ordering': ('-captured_at', '-version'),
                'unique_together': {('finding', 'version')},
            },
        ),
    ]
