# Generated by Django 4.2.24 on 2025-11-02 14:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('arpia_hunt', '0003_huntfinding_blue_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='huntfinding',
            name='last_state_snapshot_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='huntfinding',
            name='state_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='HuntFindingState',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('source_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_snapshots', to='arpia_hunt.huntfinding')),
            ],
            options={
                'ordering': ('-captured_at', '-version'),
                'unique_together': {('finding', 'version')},
            },
        ),
    ]
