# Generated by Django 4.2.24 on 2025-11-02 14:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('arpia_hunt', '0004_huntfinding_last_state_snapshot_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackTactic',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('short_description', models.TextField(blank=True)),
                ('matrix', models.CharField(choices=[('enterprise', 'Enterprise'), ('ics', 'ICS'), ('mobile', 'Mobile')], default='enterprise', max_length=24)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('matrix', 'order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AttackTechnique',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('is_subtechnique', models.BooleanField(default=False)),
                ('platforms', models.JSONField(blank=True, default=list)),
                ('datasources', models.JSONField(blank=True, default=list)),
                ('external_references', models.JSONField(blank=True, default=list)),
                ('version', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtechniques', to='arpia_hunt.attacktechnique')),
                ('tactic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='techniques', to='arpia_hunt.attacktactic')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='HuntRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommendation_type', models.CharField(choices=[('blue', 'Blue Team'), ('red', 'Red Team')], max_length=8)),
                ('title', models.CharField(max_length=160)),
                ('summary', models.TextField(blank=True)),
                ('confidence', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], default='medium', max_length=8)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('generated_by', models.CharField(choices=[('automation', 'Automação'), ('analyst', 'Analista'), ('import', 'Importação')], default='automation', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='arpia_hunt.huntfinding')),
                ('source_enrichment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='arpia_hunt.huntenrichment')),
                ('technique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='arpia_hunt.attacktechnique')),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='CveAttackTechnique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cve', models.CharField(db_index=True, max_length=40)),
                ('source', models.CharField(choices=[('heuristic', 'Heurística'), ('dataset', 'Dataset'), ('manual', 'Manual')], default='heuristic', max_length=16)),
                ('confidence', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], default='medium', max_length=8)),
                ('rationale', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cve_links', to='arpia_hunt.attacktechnique')),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='attacktactic',
            index=models.Index(fields=['matrix', 'order'], name='idx_attack_tactic_matrix_order'),
        ),
        migrations.AddIndex(
            model_name='huntrecommendation',
            index=models.Index(fields=['finding', 'recommendation_type'], name='idx_hunt_rec_finding_type'),
        ),
        migrations.AddIndex(
            model_name='huntrecommendation',
            index=models.Index(fields=['technique'], name='idx_hunt_rec_technique'),
        ),
        migrations.AddIndex(
            model_name='cveattacktechnique',
            index=models.Index(fields=['cve', 'confidence'], name='idx_cve_attack_confidence'),
        ),
        migrations.AlterUniqueTogether(
            name='cveattacktechnique',
            unique_together={('cve', 'technique', 'source')},
        ),
        migrations.AddIndex(
            model_name='attacktechnique',
            index=models.Index(fields=['tactic', 'is_subtechnique'], name='idx_attack_tech_tactic_sub'),
        ),
    ]
