# Generated by Django 4.2.24 on 2025-11-03 02:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('arpia_hunt', '0006_attacktechnique_search_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='HuntAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('priority_critical', 'Prioridade crítica'), ('automation_high', 'Heurística automática (alta confiança)'), ('blue_review', 'Revisão Blue')], max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('trigger_count', models.PositiveIntegerField(default=1)),
                ('first_triggered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_triggered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='arpia_hunt.huntfinding')),
            ],
            options={
                'ordering': ('-last_triggered_at', '-created_at'),
                'indexes': [models.Index(fields=['kind', 'is_active'], name='idx_hunt_alert_kind_active'), models.Index(fields=['finding', 'is_active'], name='idx_hunt_alert_finding_active')],
            },
        ),
        migrations.AddConstraint(
            model_name='huntalert',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('finding', 'kind'), name='uniq_active_alert_per_kind'),
        ),
    ]
