# Generated by Django 4.2.25 on 2025-10-27 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arpia_core', '0007_script_required_tool'),
        ('arpia_scan', '0003_alter_scantask_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='VulnerabilityReportEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_identifier', models.CharField(blank=True, max_length=128)),
                ('severity_distribution', models.JSONField(blank=True, default=dict)),
                ('cves', models.JSONField(blank=True, default=list)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='arpia_core.project')),
            ],
            options={
                'verbose_name': 'Relatório de Vulnerabilidades',
                'verbose_name_plural': 'Relatórios de Vulnerabilidades',
                'ordering': ['-created_at', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScanReportEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='arpia_core.project')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_entry', to='arpia_scan.scansession')),
            ],
            options={
                'verbose_name': 'Relatório de Scan',
                'verbose_name_plural': 'Relatórios de Scan',
                'ordering': ['-created_at', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('in_review', 'Em revisão'), ('final', 'Final')], default='draft', max_length=20)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_reports', to='arpia_core.project')),
            ],
            options={
                'verbose_name': 'Relatório de Projeto',
                'verbose_name_plural': 'Relatórios de Projeto',
                'ordering': ['-generated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PentestReportEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement_ref', models.CharField(blank=True, max_length=128)),
                ('findings', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='arpia_core.project')),
            ],
            options={
                'verbose_name': 'Relatório de Pentest',
                'verbose_name_plural': 'Relatórios de Pentest',
                'ordering': ['-created_at', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HuntReportEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intel_summary', models.JSONField(blank=True, default=dict)),
                ('indicators', models.JSONField(blank=True, default=list)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='arpia_core.project')),
            ],
            options={
                'verbose_name': 'Relatório de Hunt',
                'verbose_name_plural': 'Relatórios de Hunt',
                'ordering': ['-created_at', '-id'],
                'abstract': False,
            },
        ),
    ]
